[package]
name = "rust-game-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and thei r definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.7" }

